### ISSUE TITLE
可以指导一下 后端，怎么把这个前端跑起来吗？

### ISSUE THREAD

**Issue by happytsgf** [silently9527/mall-coupons#1]

**Comment by silently9527** [comment]
使用的是uniapp , 你去uniapp官网看看吧     跑起来还是很简单的

**Comment by happytsgf** [comment]
好的，我去看看，我一直在看vue的启动方式

**Comment by happytsgf** [comment]
是用 HBuilderX 开发 前端 是吗/？

**Comment by silently9527** [comment]
是的

**Comment by happytsgf** [comment]
是用的标准版还是app开发版的？

**Comment by happytsgf** [comment]
项目有初始化数据吗？ 框架 终于跑起来了

**Comment by silently9527** [comment]
没有，需要自己设置的  只有 轮播，和菜单；其他的都是读的api

**Comment by happytsgf** [comment]
老铁，有没有一个步骤说明，按操作运行，在浏览器里可以看到数据的

**Comment by happytsgf** [comment]
com.huaan9527.mall.webapi.repository 下面的资源很多没有实现的么，还是复制工程的时候少了

**Comment by happytsgf** [comment]
> 没有，需要自己设置的 只有 轮播，和菜单；其他的都是读的api
